typography_spectrum: 0.4048612709157169
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8449878597166389
  lightness: 0.5413597761653364
  saturation: 0.34824593644589186
  rhythmicContrast: 0.468915713718161
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75139
analytics:
  google: null
  facebook: null
  twitter: null
name: Museum of Acoustic Geology
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Museum of Acoustic Geology
description: Rock on.
purpose: []
