name: Museum of Acoustic Geology
favicon: null
layout_spectrum: 0.3247200979385525
typography_spectrum: 0.4048612709157169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8449878597166389
  lightness: 0.5413597761653364
  saturation: 0.34824593644589186
  rhythmicContrast: 0.468915713718161
purpose: []
